import type { PlayerStats } from '../types/game';
import { HUSTLES } from '../config/hustles/base';
import { BACKGROUNDS } from '../config/backgrounds';

export const getInitialStats = (
  difficulty: 1 | 2 | 3,
  backgroundId?: string,
  categoryId?: string,
  variationId?: string,
  unlockedUpgrades: string[] = []
): PlayerStats => {
  const baseStats: PlayerStats = {
    runId: crypto.randomUUID?.() || Math.random().toString(36).substring(2, 15),
    avatarId: 'av_m1',
    worldFeed: [],
    ambitions: [],
    consequences: [],
    financialDebts: [],
    activeLiveEvent: null,
    completedLiveEvents: [],
    bag: 0,
    clout: 0,
    aura: 0,
    backgroundId,
    categoryId,
    variationId,
    chosenBackground: undefined,
    chosenBackgroundCategory: categoryId,
    chosenBackgroundVariation: variationId,
    mentalHealth: 100,
    heat: 0,
    month: 0,
    lastAdvisorPopupMonth: -1,
    advisorQueue: [],
    currentTier: 'MUD',
    hustleLevels: {},
    hustleBranchIds: {},
    masteredHustles: [],
    flexAssets: {},
    unlockedAchievements: [],
    rentalCount: 0,
    rentPortfolioCount: 0,
    flipCount: 0,
    vendingCount: 0,
    passiveLaborYield: 0,
    mentalShieldTurns: 0,
    artists: [],
    scoutedTalentPool: [],
    activeMinigame: null,
    endgameTracks: {
      realEstateAcquisitions: [],
      globalFleetCount: 0,
      automatedHustleIds: [],
      techStartupValuation: 1000
    },
    rolodex: [],
    foundersBacked: [],
    conglomerateCEOs: {},
    conglomerateCandidates: [],
    npcs: [],
    rareTechStockpile: 0,
    algorithmicLogs: 0,
    grammyCount: 0,
    recordLabelLevel: 1,
    festivalChoices: {
      headliner: 'budget',
      venue: 'small',
      marketing: 'basic',
      insurance: false,
    },
    dataAnalyticsChoice: 'consumer',
    cryptoStrategy: 'solo',
    vaStaff: 5,
    vaTraining: 'none',
    vaClient: 'small',
    realEstateType: 'residential',
    realEstateLeverage: 0,
    realEstateStrategy: 'hold',
    vcStage: 'seed',
    vcSector: 'tech',
    vcInvestment: 1,
    legacyPoints: 0,
    filmGenre: 'action',
    filmBudget: 'medium',
    spaceCompany: 'asteroid',
    philanthropyDonation: 10000000,
    electoralVotes: 0,
    foreignRelations: 50,
    worldPeace: 50,
    voterTurnout: 50,
    campaignStage: 1,
    campaignPlatform: 'economy',
    campaignVP: '',
    campaignDelegates: 0,
    approvalRating: 50,
    gdp: 100,
    inflation: 2,
    nationalDebt: 60,
    federalBudget: 50000000,
    congressSupport: 50,
    demographicApproval: {
      'Economy': 50,
      'Healthcare': 50,
      'Foreign Policy': 50,
      'National Security': 50,
      'Civil Rights': 50,
      'Latinos': 50,
      'Seniors': 50,
      'Veterans': 50
    },
    regionalApproval: {
      'Northeast': 50,
      'South': 50,
      'Midwest': 50,
      'West': 50
    },
    prePresidencyTier: null,
    crushedRivals: [],
    marketLeaderTiers: [],
    approvalFloor: 0,
    scandalRiskBonus: 0,
    sotuHistory: [],
    presidentialDiary: [],
    presidentMonth: 0,
    isSecondTerm: false,
    isReElectionPhase: false,
    termComplete: false,
    pendingTermEnd: false,
    scandalCount: 0,
    cabinet: {},
    activeCrises: [],
    presidentialMarketControl: null,
    pendingPresidentialImpacts: [],
    marketCycle: {
      realEstate: 'normal',
      vc: {
        tech: 'normal',
        biotech: 'normal',
        energy: 'normal',
      },
    },
    monthsSinceCycleChange: 0,
    dynamicPassives: {},
    lastPassiveBreakdown: undefined,
    lastStatBreakdown: undefined,
    activeSpecializationId: null,
    specializationHistory: [],
    rivals: [
      {
        id: 'rival_mud',
        name: 'Marcus',
        netWorth: 5000,
        currentBid: 0,
        isNpc: true,
        tier: 'MUD',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.3,
        aggression: 0.4,
        intelligence: 0.5,
        ambition: 0.4,
        ethics: 0.7,
        politicalLeaning: 'center',
        preferredIndustries: ['Food', 'Retail'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Food']
      },
      {
        id: 'rival_street',
        name: 'Sarah',
        netWorth: 50000,
        currentBid: 0,
        isNpc: true,
        tier: 'STREET',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.6,
        aggression: 0.5,
        intelligence: 0.6,
        ambition: 0.7,
        ethics: 0.5,
        politicalLeaning: 'libertarian',
        preferredIndustries: ['Retail', 'Real Estate'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Retail']
      },
      {
        id: 'rival_startup',
        name: 'David',
        netWorth: 500000,
        currentBid: 0,
        isNpc: true,
        tier: 'STARTUP',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.8,
        aggression: 0.7,
        intelligence: 0.8,
        ambition: 0.9,
        ethics: 0.3,
        politicalLeaning: 'right',
        preferredIndustries: ['Technology', 'Finance'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Technology']
      },
      {
        id: 'rival_corp',
        name: 'Emily',
        netWorth: 5000000,
        currentBid: 0,
        isNpc: true,
        tier: 'CORPORATE',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.5,
        aggression: 0.8,
        intelligence: 0.9,
        ambition: 0.95,
        ethics: 0.2,
        politicalLeaning: 'right',
        preferredIndustries: ['Entertainment', 'Finance', 'Real Estate'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Entertainment']
      },
      {
        id: 'rival_1',
        name: 'Sterling Vane',
        netWorth: 50000000,
        currentBid: 0,
        isNpc: true,
        tier: 'ELITE',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.4,
        aggression: 0.6,
        intelligence: 0.7,
        ambition: 0.8,
        ethics: 0.4,
        politicalLeaning: 'center',
        preferredIndustries: ['Finance', 'Technology'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Finance']
      },
      {
        id: 'rival_2',
        name: 'Morgan Thorne',
        netWorth: 75000000,
        currentBid: 0,
        isNpc: true,
        tier: 'MOGUL',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.5,
        aggression: 0.7,
        intelligence: 0.8,
        ambition: 0.85,
        ethics: 0.3,
        politicalLeaning: 'left',
        preferredIndustries: ['Entertainment', 'Media'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Media']
      },
      {
        id: 'rival_3',
        name: 'Elena Rosso',
        netWorth: 120000000,
        currentBid: 0,
        isNpc: true,
        tier: 'PRESIDENT',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.6,
        aggression: 0.8,
        intelligence: 0.95,
        ambition: 1.0,
        ethics: 0.1,
        politicalLeaning: 'left',
        preferredIndustries: ['Politics', 'Finance'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Politics']
      },
      {
        id: 'rival_4',
        name: 'Victor Draken',
        netWorth: 250000000,
        currentBid: 0,
        isNpc: true,
        tier: 'OPEN',
        vengeance: 1,
        clout: Math.floor(50 + Math.random() * 150),
        riskTolerance: 0.7,
        aggression: 0.9,
        intelligence: 0.9,
        ambition: 1.0,
        ethics: 0.15,
        politicalLeaning: 'libertarian',
        preferredIndustries: ['Technology', 'Finance', 'Real Estate'],
        relationshipWithPlayer: 0,
        sabotagedCount: 0,
        helpedCount: 0,
        businesses: [],
        propertiesOwned: 0,
        companiesAcquired: [],
        mediaCompaniesOwned: 0,
        employeesHired: 0,
        politicalInfluence: 0,
        passiveIncome: 0,
        industries: ['Technology']
      },
    ],
    rivalThreats: {},
    activeChallenges: [],
    activeSentiment: null,
    activeWorldEvent: null,
    worldEventCooldown: 0,
    completedNarrativeEvents: [],
    biography: [],
    recordedBioKeys: [],
    history: [],
    activeNarrative: null,
    narrativeCooldown: 0,
    lastCharacterId: undefined,
    lastArcId: undefined,
    arcLastFired: {},
    monthsSinceLastEvent: 0,
    narrativeFlags: {},
    originBonus: null,
    actionLog: [],
    milestones: [],
    events: [],
    collectedDeathBadges: [],
    deathCount: 0,
    arrestCount: 0,
    tierBadges: [],
    pendingFlexOffer: null,
    flexOfferCooldown: 0,
    seenFlexThresholds: [],
    pendingAnnualStatement: false,
    annualCashEarned: 0,
    annualCashSpent: 0,
    annualHustlesRun: 0,
    tierStats: {},
    hustlePlays: {},
    completedDailyChallengesCount: 0,
    totalChallengesCompleted: 0,
    totalHustlesCompleted: 0,
    inJail: false,
    isIncarcerated: false,
    jailMonthsRemaining: 0,
    jailSentenceTotal: 0,
    jailCharge: '',
    tutorialStep: 0,
    isTutorialSkipped: false,
    guidanceSettings: 'Recommended',
    unlockedLegacyUpgradeIds: [],
    stats: {
      totalHustles: 0,
      successfulHustles: 0,
      lifetimeEarnings: 0,
    },
  };

  let stats: PlayerStats;

  if (difficulty === 1) { // Trust Fund
    stats = {
      ...baseStats,
      bag: 25000,
      clout: 30,
      aura: 30,
      currentTier: 'STREET',
    };
  } else if (difficulty === 2) { // Middle Grind
    stats = {
      ...baseStats,
      bag: 5000,
      clout: 15,
      aura: 15,
      currentTier: 'MUD',
    };
  } else { // Grinder (default)
    stats = {
      ...baseStats,
      bag: 1000,
      clout: 5,
      aura: 5,
      currentTier: 'MUD',
    };
  }

  if (backgroundId) {
    const bg = BACKGROUNDS.find(b => b.id === backgroundId);
    if (bg) {
      stats.bag += bg.starterBag;
      stats.clout += bg.starterClout;
      stats.aura += bg.starterAura;
      stats.chosenBackground = bg.id;
      stats.originBonus = bg.originBonus;
    }
  }

  // Apply Legacy Upgrades
  stats.unlockedLegacyUpgradeIds = unlockedUpgrades;
  if (unlockedUpgrades.includes('extra_cash')) stats.bag += 5000;
  if (unlockedUpgrades.includes('extra_clout')) stats.clout += 50;
  if (unlockedUpgrades.includes('extra_aura')) stats.aura += 50;
  if (unlockedUpgrades.includes('early_vending')) stats.vendingCount += 1;

  return stats;
};

export const getUnlockedHustles = (difficulty: 1 | 2 | 3, unlockedUpgrades: string[] = []): Record<string, boolean> => {
  const allMud = [
    'r_labor',
    'r_delivery',
    'r_plasma',
    'r_ghost_mode',
    'r_scrap',
    'r_flyers',
    'h_sign_spinner',
    'r_sleep',
    'r_vending',
    'street_eats',
    'cleaning',
  ];

  if (unlockedUpgrades.includes('unique_hustle_deli')) {
    allMud.push('unique_hustle_deli');
  }

  if (difficulty === 1) {
    // Trust Fund: all hustles unlocked
    return Object.keys(HUSTLES).reduce((acc, id) => ({ ...acc, [id]: true }), {});
  } else {
    // Both Middle Grind and Grinder now get all MUD hustles
    return allMud.reduce((acc, id) => ({ ...acc, [id]: true }), {
        ...(unlockedUpgrades.includes('unique_hustle_deli') ? { unique_hustle_deli: true } : {})
    });
  }
};
