import type { Badge } from '../types/game';

export const HUSTLE_BADGES: Record<string, Badge> = {
  r_labor: {
    id: 'badge_labor',
    hustleId: 'r_labor',
    name: 'Land King',
    description: 'Flip 50 properties. Or just one really big one.',
    icon: '🏢',
    buff: { type: 'yield', value: 1.10 },
    futureBenefit: '+5% Labor Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  r_delivery: {
    id: 'badge_delivery',
    hustleId: 'r_delivery',
    name: 'Speed Demon',
    description: 'Every red light is just a suggestion.',
    icon: '🛵',
    buff: { type: 'yield', value: 1.05 },
    futureBenefit: '+5% Infrastructure Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  r_plasma: {
    id: 'badge_plasma',
    hustleId: 'r_plasma',
    name: 'Essence Merchant',
    description: 'You are literally made of money. Sort of.',
    icon: '🩸',
    buff: { type: 'mental', value: 0.90 }, // 10% less mental hit
    futureBenefit: '+5% Healthcare Reform effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  r_vending: {
    id: 'badge_vending',
    hustleId: 'r_vending',
    name: 'Snack Sovereign',
    description: 'Owned every machine in the tri-state area.',
    icon: '🥤',
    buff: { type: 'yield', value: 1.05 },
    futureBenefit: '+5% Small Business Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  r_ghost_mode: {
    id: 'badge_ghost',
    hustleId: 'r_ghost_mode',
    name: 'Untouchable',
    description: 'If they can\'t see you, they can\'t tax you.',
    icon: '👻',
    buff: { type: 'heat', value: 0.80 }, // 20% less heat
    futureBenefit: '+5% Security Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  r_scrap: {
    id: 'badge_scrap',
    hustleId: 'r_scrap',
    name: 'Magnet Master',
    description: 'Found 10 rare metals and 10,000 rusty nails.',
    icon: '🔧',
    buff: { type: 'yield', value: 1.15 },
    futureBenefit: '+5% Crisis Response effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  r_flyers: {
    id: 'badge_flyers',
    hustleId: 'r_flyers',
    name: 'Paper Storm',
    description: 'Littering? No, I call it aggressive marketing.',
    icon: '📄',
    buff: { type: 'clout', value: 1.10 },
    futureBenefit: '+5% Voter Outreach effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  street_eats: {
    id: 'badge_eats',
    hustleId: 'street_eats',
    name: 'Taco Titan',
    description: 'Served 10,000 customers. Only 2 cases of food poisoning!',
    icon: '🌮',
    buff: { type: 'yield', value: 1.10 },
    futureBenefit: '+5% Working Class Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  cc: {
    id: 'badge_cc',
    hustleId: 'cc',
    name: 'Viral Lord',
    description: 'The algorithm is your puppet.',
    icon: '📱',
    buff: { type: 'clout', value: 1.15 },
    futureBenefit: '+10% Digital Infrastructure effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  pod: {
    id: 'badge_pod',
    hustleId: 'pod',
    name: 'Voice of Reason',
    description: 'Talking for 4 hours straight actually pays off.',
    icon: '🎙️',
    buff: { type: 'clout', value: 1.10 },
    futureBenefit: '+10% Propaganda Push effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  drop: {
    id: 'badge_drop',
    hustleId: 'drop',
    name: 'Supply Chain God',
    description: 'Shipping air from China at a 400% markup.',
    icon: '📦',
    buff: { type: 'yield', value: 1.10 },
    futureBenefit: '+5% Trade Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  vintage: {
    id: 'badge_vintage',
    hustleId: 'vintage',
    name: 'Archival Ace',
    description: 'That\'s not a stain, it\'s "character".',
    icon: '🧥',
    buff: { type: 'aura', value: 1.10 },
    futureBenefit: '+5% Cultural Heritage Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  techFlip: {
    id: 'badge_tech',
    hustleId: 'techFlip',
    name: 'Silicon Surfer',
    description: 'Reach $1M revenue from tech flipping.',
    icon: '💻',
    buff: { type: 'yield', value: 1.10 },
    futureBenefit: '+5% Data & Crypto Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  audio: {
    id: 'badge_audio',
    hustleId: 'audio',
    name: 'Platinum Producer',
    description: 'Win 5 Grammys. Or just buy them.',
    icon: '🎹',
    buff: { type: 'clout', value: 1.15 },
    futureBenefit: '+5% Festival effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  sw: {
    id: 'badge_sw',
    hustleId: 'sw',
    name: 'Hype Beast',
    description: 'You sold a plain white tee for $500. Legend.',
    icon: '👕',
    buff: { type: 'aura', value: 1.15 },
    futureBenefit: '+10% Grassroots Campaign effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  saas_mvp: {
    id: 'badge_saas',
    hustleId: 'saas_mvp',
    name: 'Code Crusader',
    description: 'Fixed one bug, created ten more. Scaled anyway.',
    icon: '💻',
    buff: { type: 'yield', value: 1.10 },
    futureBenefit: '+10% Digital Infrastructure effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  global_franchise: {
    id: 'badge_franchise',
    hustleId: 'global_franchise',
    name: 'Golden Arches',
    description: 'The sun never sets on your burger empire.',
    icon: '🍔',
    buff: { type: 'yield', value: 1.10 },
    futureBenefit: '+5% Economic Stability Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  smm: {
    id: 'badge_smm',
    hustleId: 'smm',
    name: 'Agency Architect',
    description: 'Managed 100 accounts without a single password leak.',
    icon: '📈',
    buff: { type: 'clout', value: 1.10 },
    futureBenefit: '+10% Propaganda Push effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  gig: {
    id: 'badge_gig',
    hustleId: 'gig',
    name: 'Logistics Legend',
    description: 'Your fleet delivers faster than the speed of light.',
    icon: '🚚',
    buff: { type: 'yield', value: 1.05 },
    futureBenefit: '+5% Infrastructure Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  meme: {
    id: 'badge_meme',
    hustleId: 'meme',
    name: 'Diamond Hands',
    description: 'Held through a 99% crash and came out on top.',
    icon: '🪙',
    buff: { type: 'aura', value: 1.15 },
    futureBenefit: '+5% Data & Crypto Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  festival: {
    id: 'badge_festival',
    hustleId: 'festival',
    name: 'Woodstock Wizard',
    description: 'Organized the greatest show on Earth.',
    icon: '🎸',
    buff: { type: 'aura', value: 1.10 },
    futureBenefit: '+10% Cultural Heritage Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  lobbying: {
    id: 'badge_lobbying',
    hustleId: 'lobbying',
    name: 'Kingmaker',
    description: 'Laws are just suggestions for you.',
    icon: '🏛️',
    buff: { type: 'heat', value: 0.85 },
    futureBenefit: '+10% Congress Support from Executive Orders',
    relevantTier: 'PRESIDENT',
  },
  hedgefund: {
    id: 'badge_hedge',
    hustleId: 'hedgefund',
    name: 'Market Manipulator',
    description: 'You don\'t predict the market, you ARE the market.',
    icon: '📊',
    buff: { type: 'yield', value: 1.15 },
    futureBenefit: '+5% Economic Stability Policy effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  film_studio: {
    id: 'badge_film',
    hustleId: 'film_studio',
    name: 'Oscar Owner',
    description: 'Every movie you touch turns to gold.',
    icon: '🎬',
    buff: { type: 'clout', value: 1.20 },
    futureBenefit: '+10% Propaganda Push effectiveness in President tier',
    relevantTier: 'PRESIDENT',
  },
  president_campaign: {
    id: 'badge_president',
    hustleId: 'president_campaign',
    name: 'Commander in Chief',
    description: 'The ultimate hustle. You won the country.',
    icon: '🇺🇸',
    buff: { type: 'aura', value: 1.25 },
    futureBenefit: '+10% Legacy Point gain during second term',
    relevantTier: 'PRESIDENT',
  }
};
