import type { CabinetMember } from '../types/game';

export interface CabinetCandidate extends Omit<CabinetMember, 'role' | 'loyalty' | 'bonus'> {
  id: string;
  preferredRoles: string[];
  baseBonusValue: number;
}

export const CABINET_CANDIDATES: CabinetCandidate[] = [
  {
    id: 'cand_ashley_weaver',
    characterId: 'char_ashley',
    name: 'Ashley Weaver',
    avatarId: 'av_f2',
    previousCareer: 'Investigative Journalist',
    competence: 85,
    integrity: 95,
    popularity: 80,
    corruptionRisk: 5,
    ambition: 60,
    personalityTraits: ['Relentless', 'Ethical', 'Sharp'],
    bio: 'A former top-tier investigative journalist who knows how to handle the media and sniff out a story before it breaks.',
    preferredRoles: ['press'],
    baseBonusValue: 15
  },
  {
    id: 'cand_lawrence_chen',
    characterId: 'char_chen',
    name: 'Lawrence Chen',
    avatarId: 'av_m4',
    previousCareer: 'Venture Capitalist',
    competence: 92,
    integrity: 70,
    popularity: 65,
    corruptionRisk: 25,
    ambition: 75,
    personalityTraits: ['Calculating', 'Data-driven', 'Influential'],
    bio: 'A high-stakes investor with an unparalleled understanding of market dynamics and capital flow.',
    preferredRoles: ['treasury'],
    baseBonusValue: 20
  },
  {
    id: 'cand_victor_kane',
    characterId: 'char_victor',
    name: 'Victor Kane',
    avatarId: 'av_m2',
    previousCareer: 'Conglomerate CEO',
    competence: 98,
    integrity: 30,
    popularity: 50,
    corruptionRisk: 60,
    ambition: 95,
    personalityTraits: ['Ruthless', 'Strategic', 'Arrogant'],
    bio: 'One of the most powerful CEOs in the country. His results are unquestionable, but his methods are often shrouded in controversy.',
    preferredRoles: ['treasury', 'state'],
    baseBonusValue: 25
  },
  {
    id: 'cand_silas_whitaker',
    characterId: 'char_whitaker',
    name: 'Gen. Silas Whitaker',
    avatarId: 'av_m3',
    previousCareer: 'Four-Star General',
    competence: 90,
    integrity: 85,
    popularity: 75,
    corruptionRisk: 10,
    ambition: 50,
    personalityTraits: ['Disciplined', 'Blunt', 'Strategic'],
    bio: 'A decorated war hero and former Chairman of the Joint Chiefs. He views national security through a lens of absolute discipline.',
    preferredRoles: ['defense'],
    baseBonusValue: 18
  },
  {
    id: 'cand_sofia_ramirez',
    characterId: 'char_sofia',
    name: 'Sofia Ramirez',
    avatarId: 'av_f3',
    previousCareer: 'City Mayor / Senator',
    competence: 80,
    integrity: 55,
    popularity: 90,
    corruptionRisk: 40,
    ambition: 90,
    personalityTraits: ['Charismatic', 'Pragmatic', 'Eloquent'],
    bio: 'A rising political star with a massive base of popular support and a deep understanding of legislative maneuvering.',
    preferredRoles: ['state', 'press'],
    baseBonusValue: 12
  },
  {
    id: 'cand_sarah_jenkins',
    characterId: 'char_sarah',
    name: 'Sarah Jenkins',
    avatarId: 'av_f2',
    previousCareer: 'Union Leader',
    competence: 75,
    integrity: 90,
    popularity: 85,
    corruptionRisk: 15,
    ambition: 65,
    personalityTraits: ['Tough', 'Uncompromising', 'Protective'],
    bio: 'A fierce advocate for the working class who can mobilize millions. She brings a unique perspective to the administration.',
    preferredRoles: ['treasury', 'press'],
    baseBonusValue: 14
  },
  {
    id: 'cand_elias_blackwood',
    characterId: 'char_blackwood',
    name: 'Elias Blackwood',
    avatarId: 'av_m3',
    previousCareer: 'Intelligence Director',
    competence: 95,
    integrity: 60,
    popularity: 40,
    corruptionRisk: 30,
    ambition: 70,
    personalityTraits: ['Secretive', 'Cynical', 'Omnipresent'],
    bio: 'The ultimate spymaster. He knows where all the bodies are buried and how to keep yours from joining them.',
    preferredRoles: ['defense', 'state'],
    baseBonusValue: 22
  },
  {
    id: 'cand_margaret_holloway',
    characterId: 'char_holloway',
    name: 'Judge Margaret Holloway',
    avatarId: 'av_f4',
    previousCareer: 'Supreme Court Justice',
    competence: 96,
    integrity: 100,
    popularity: 70,
    corruptionRisk: 0,
    ambition: 40,
    personalityTraits: ['Impartial', 'Intellectual', 'Formidable'],
    bio: 'A legal titan known for her unwavering commitment to the rule of law. Her presence grants immediate legitimacy to any policy.',
    preferredRoles: ['state'],
    baseBonusValue: 16
  },
  {
    id: 'cand_fiona_glass',
    characterId: 'char_fiona',
    name: 'Fiona Glass',
    avatarId: 'av_f4',
    previousCareer: 'Forensic Auditor',
    competence: 88,
    integrity: 98,
    popularity: 55,
    corruptionRisk: 5,
    ambition: 55,
    personalityTraits: ['Relentless', 'Analytical', 'Dry'],
    bio: 'An expert in following the money. She can spot corruption from a mile away and is feared by every accountant in the country.',
    preferredRoles: ['treasury'],
    baseBonusValue: 18
  },
  {
    id: 'cand_arthur_bennett',
    characterId: 'char_bennett',
    name: 'Dr. Arthur Bennett',
    avatarId: 'av_m3',
    previousCareer: 'Business School Dean',
    competence: 82,
    integrity: 80,
    popularity: 60,
    corruptionRisk: 15,
    ambition: 45,
    personalityTraits: ['Traditional', 'Scholarly', 'Influential'],
    bio: 'An academic heavyweight who has mentored the next generation of business leaders. He brings prestige and theory to the table.',
    preferredRoles: ['treasury'],
    baseBonusValue: 12
  },
  {
    id: 'cand_elena_vance',
    characterId: 'char_elena',
    name: 'Elena Vance',
    avatarId: 'av_f4',
    previousCareer: 'Corporate Fixer',
    competence: 94,
    integrity: 40,
    popularity: 35,
    corruptionRisk: 50,
    ambition: 80,
    personalityTraits: ['Efficient', 'Cold', 'Discreet'],
    bio: 'A shadow player who specializes in making problems disappear. Highly effective, but operates in a moral grey area.',
    preferredRoles: ['defense', 'state'],
    baseBonusValue: 20
  },
  {
    id: 'cand_alistair_clark',
    characterId: 'char_clark',
    name: 'Alistair Clark',
    avatarId: 'av_m4',
    previousCareer: 'Corporate Lawyer',
    competence: 90,
    integrity: 50,
    popularity: 45,
    corruptionRisk: 45,
    ambition: 85,
    personalityTraits: ['Ruthless', 'Precise', 'Arrogant'],
    bio: 'The "Closer." A legal shark who has never met a contract he couldn\'t manipulate or an opponent he couldn\'t crush.',
    preferredRoles: ['state', 'treasury'],
    baseBonusValue: 18
  },
  {
    id: 'cand_anya_singh',
    characterId: 'char_singh',
    name: 'Anya Singh',
    avatarId: 'av_f4',
    previousCareer: 'Space Tech CEO',
    competence: 92,
    integrity: 85,
    popularity: 80,
    corruptionRisk: 10,
    ambition: 75,
    personalityTraits: ['Visionary', 'Intense', 'Risk-tolerant'],
    bio: 'A pioneer of the second space age. She brings a futuristic perspective and massive technological expertise to the cabinet.',
    preferredRoles: ['defense', 'treasury'],
    baseBonusValue: 20
  },
  {
    id: 'cand_marcus_stone',
    characterId: 'char_stone',
    name: 'Marcus Stone',
    avatarId: 'av_m1',
    previousCareer: 'Campaign Manager',
    competence: 85,
    integrity: 20,
    popularity: 45,
    corruptionRisk: 75,
    ambition: 90,
    personalityTraits: ['Cynical', 'High-energy', 'Predatory'],
    bio: 'A legendary political operative who has won some of the toughest elections in history. He plays dirty and he plays to win.',
    preferredRoles: ['press', 'state'],
    baseBonusValue: 15
  },
  {
    id: 'cand_kenji_tanaka',
    characterId: 'char_tanaka',
    name: 'Kenji Tanaka',
    avatarId: 'av_m4',
    previousCareer: 'Foreign Prime Minister',
    competence: 88,
    integrity: 90,
    popularity: 75,
    corruptionRisk: 10,
    ambition: 40,
    personalityTraits: ['Diplomatic', 'Observant', 'Firm'],
    bio: 'A master of international relations and soft power. His appointment would be a massive signal of global cooperation.',
    preferredRoles: ['state'],
    baseBonusValue: 18
  },
  // Generic but named candidates
  {
    id: 'cand_generic_1',
    name: 'Adm. Sarah Lofton',
    avatarId: 'av_f1',
    previousCareer: 'Naval Admiral',
    competence: 82,
    integrity: 90,
    popularity: 70,
    corruptionRisk: 5,
    ambition: 45,
    personalityTraits: ['Disciplined', 'Methodical', 'Brave'],
    bio: 'A career naval officer known for her cool head under pressure and impeccable service record.',
    preferredRoles: ['defense'],
    baseBonusValue: 15
  },
  {
    id: 'cand_generic_2',
    name: 'Robert "Bob" Miller',
    avatarId: 'av_m2',
    previousCareer: 'Wall Street Analyst',
    competence: 85,
    integrity: 45,
    popularity: 40,
    corruptionRisk: 55,
    ambition: 85,
    personalityTraits: ['Fast-talking', 'Ambitious', 'Nervous'],
    bio: 'A former wunderkind of Wall Street who understands the numbers but occasionally cuts corners to get them.',
    preferredRoles: ['treasury'],
    baseBonusValue: 15
  },
  {
    id: 'cand_generic_3',
    name: 'Dr. Elena Rossi',
    avatarId: 'av_f3',
    previousCareer: 'Public Health Director',
    competence: 78,
    integrity: 95,
    popularity: 80,
    corruptionRisk: 5,
    ambition: 50,
    personalityTraits: ['Compassionate', 'Organized', 'Tireless'],
    bio: 'A dedicated public servant who has managed multiple health crises with transparency and empathy.',
    preferredRoles: ['press'],
    baseBonusValue: 12
  }
];
