import type { Character } from '../types/game';

export const CHARACTERS: Character[] = [
  {
    id: 'char_marcus',
    name: 'Marcus Miller',
    nickname: 'Mook',
    portraitId: 'av_m1',
    background: 'Your closest friend from the mud blocks. He knows your secrets, your shames, and where the bodies are buried. He\'s the only one who still calls you by your old name.',
    personality: 'Loyal to a fault, reckless, survives on instinct.',
    profession: 'Street Fixer',
    speakingStyle: 'Slang-heavy, informal, direct.',
    moralAlignment: 'Chaotic Good',
    preferredIndustries: ['Logistics', 'Security'],
    strengths: ['Loyalty', 'Underworld Connections'],
    weaknesses: ['Impulsive', 'Short-term Thinking'],
    relationshipTags: ['Childhood Friend', 'Confidant'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_ashley',
    name: 'Ashley Weaver',
    portraitId: 'av_f2',
    background: 'Ambitious investigative journalist for the Metro Gazette. Always looking for the next big scoop.',
    personality: 'Persistent, ethical, inquisitive.',
    profession: 'Investigative Journalist',
    speakingStyle: 'Professional, sharp, questioning.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Media', 'Public Relations'],
    strengths: ['Information Gathering', 'Public Influence'],
    weaknesses: ['Idealistic', 'Risk-averse'],
    relationshipTags: ['Media Contact', 'Watchdog'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE', 'ELITE', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_cole',
    name: 'Silas Cole',
    nickname: 'Detective',
    portraitId: 'av_m3',
    background: 'A veteran detective with a grudge against the "new money" taking over the city.',
    personality: 'Cynical, observant, incorruptible.',
    profession: 'Police Detective',
    speakingStyle: 'Gruff, concise, weary.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Security', 'Legal'],
    strengths: ['Persistence', 'Legal Authority'],
    weaknesses: ['Rigid', 'Technophobic'],
    relationshipTags: ['Law Enforcement', 'Antagonist'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE', 'ELITE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_chen',
    name: 'Lawrence Chen',
    portraitId: 'av_m4',
    background: 'A titan of high-stakes venture capital. He believes that markets are driven by individual will, and he\'s betting that your will is stronger than the rest. He will be your most valuable ally or your coldest executioner.',
    personality: 'Calculating, demanding, influential.',
    profession: 'Venture Capitalist',
    speakingStyle: 'Corporate, data-driven, assertive.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Technology', 'Finance'],
    strengths: ['Capital Access', 'Strategic Scaling'],
    weaknesses: ['Apathy', 'Profit-Obsession'],
    relationshipTags: ['Investor', 'Mentor'],
    firstAppearanceTier: 'STARTUP',
    futureAppearanceTiers: ['CORPORATE', 'ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_maya',
    name: 'Maya Vane',
    portraitId: 'av_f1',
    background: 'Your younger sister and the only person who can look you in the eye and tell you you\'re wrong. She believes in people, while you believe in profit.',
    personality: 'Idealistic, grounding, the keeper of your conscience.',
    profession: 'Social Worker',
    speakingStyle: 'Warm, earnest, persuasive.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Philanthropy', 'Public Service'],
    strengths: ['Empathy', 'Community Trust'],
    weaknesses: ['Soft-hearted', 'Financial Naivety'],
    relationshipTags: ['Family', 'Moral Compass'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP', 'ELITE', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_victor',
    name: 'Victor Kane',
    portraitId: 'av_m2',
    background: 'The apex predator of the corporate world. He views your rise not as a success story, but as a breach of his territory that must be corrected.',
    personality: 'Coldly strategic, predatory, views empathy as a structural weakness.',
    profession: 'Conglomerate CEO',
    speakingStyle: 'Refined, menacing, condescending.',
    moralAlignment: 'Lawful Evil',
    preferredIndustries: ['Finance', 'Real Estate', 'Manufacturing'],
    strengths: ['Political Leverage', 'Monopolistic Power'],
    weaknesses: ['Hubris', 'Underestimating Rivals'],
    relationshipTags: ['Rival', 'Industry Titan'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL', 'PRESIDENT'],
    initialStatus: 'rival'
  },
  {
    id: 'char_sofia',
    name: 'Sofia Ramirez',
    portraitId: 'av_f3',
    background: 'A rising political star with eyes on the Mayor\'s office and beyond. She needs powerful backers.',
    personality: 'Charismatic, ambitious, pragmatic.',
    profession: 'Politician',
    speakingStyle: 'Eloquent, inspirational, calculated.',
    moralAlignment: 'Neutral Evil',
    preferredIndustries: ['Politics', 'Public Relations'],
    strengths: ['Public Speaking', 'Political Maneuvering'],
    weaknesses: ['Opportunistic', 'Image-Obsessed'],
    relationshipTags: ['Political Ally', 'Power Broker'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_ghost',
    name: 'Ghost',
    portraitId: 'av_f4',
    background: 'An anonymous hacker-activist who specializes in corporate espionage and digital sabotage.',
    personality: 'Enigmatic, libertarian, brilliant.',
    profession: 'Elite Hacker',
    speakingStyle: 'Cryptic, technical, detached.',
    moralAlignment: 'Chaotic Neutral',
    preferredIndustries: ['Technology', 'Security'],
    strengths: ['Cyber Warfare', 'Information Sabotage'],
    weaknesses: ['Paranoid', 'Lack of Physical Presence'],
    relationshipTags: ['Digital Asset', 'Mercenary'],
    firstAppearanceTier: 'STARTUP',
    futureAppearanceTiers: ['CORPORATE', 'ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_leo',
    name: 'Leo Thorne',
    portraitId: 'av_m1',
    background: 'The world\'s most popular lifestyle influencer. He can make or break a brand with a single post.',
    personality: 'Vain, energetic, fickle.',
    profession: 'Lifestyle Influencer',
    speakingStyle: 'Hyper-energetic, trendy, superficial.',
    moralAlignment: 'Chaotic Neutral',
    preferredIndustries: ['Entertainment', 'Retail'],
    strengths: ['Viral Reach', 'Trendsetting'],
    weaknesses: ['Vain', 'Fragile Ego'],
    relationshipTags: ['Marketing Asset', 'Socialite'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_sarah',
    name: 'Sarah Jenkins',
    portraitId: 'av_f2',
    background: 'Leader of the United Workers Union. She\'s the only one standing between you and total labor control.',
    personality: 'Tough, uncompromising, protective.',
    profession: 'Union Leader',
    speakingStyle: 'Powerful, blunt, uncompromising.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Manufacturing', 'Transport', 'Logistics'],
    strengths: ['Mass Mobilization', 'Negotiation'],
    weaknesses: ['Stubborn', 'Funding Shortages'],
    relationshipTags: ['Labor Representative', 'Political Force'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_volkov',
    name: 'Mikhail Volkov',
    nickname: 'The Bear',
    portraitId: 'av_m3',
    background: 'Leader of a powerful foreign nation with significant interests in your city\'s tech sector.',
    personality: 'Stoic, nationalist, ruthless.',
    profession: 'Foreign Head of State',
    speakingStyle: 'Formal, authoritative, heavy accent.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Technology', 'Manufacturing', 'Energy'],
    strengths: ['Sovereign Power', 'Strategic Patience'],
    weaknesses: ['Geopolitical Constraints', 'Over-Reliance on Force'],
    relationshipTags: ['Foreign Leader', 'Global Power'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_elena',
    name: 'Elena Vance',
    portraitId: 'av_f4',
    background: 'A corporate fixer who handles the problems that money alone can\'t solve.',
    personality: 'Efficient, cold, discreet.',
    profession: 'Corporate Fixer',
    speakingStyle: 'Whispered, clinical, brief.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Legal', 'Security', 'Finance'],
    strengths: ['Discretion', 'Problem Solving'],
    weaknesses: ['Moral Void', 'Expensive Retainer'],
    relationshipTags: ['Problem Solver', 'Shadow Asset'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_pops',
    name: 'Arthur "Pops" Jenkins',
    nickname: 'Pops',
    portraitId: 'av_m3',
    background: 'The unofficial heart of the old neighborhood. He has seen empires rise and fall while he tended his garden, and he fears you might be the next one to forget the value of the dirt you came from.',
    personality: 'Wise, patient, stubborn.',
    profession: 'Community Elder',
    speakingStyle: 'Slow, metaphorical, paternal.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Food', 'Philanthropy'],
    strengths: ['Historical Knowledge', 'Deep Respect'],
    weaknesses: ['Physical Health', 'Resistance to Change'],
    relationshipTags: ['Mentor', 'Neighborhood Anchor'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP', 'CORPORATE', 'ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_slick',
    name: 'Terrence "Slick" Reed',
    nickname: 'Slick',
    portraitId: 'av_m2',
    background: 'A street-level gambler who always has a "sure thing" tip. Usually ends up running from someone.',
    personality: 'Charismatic, nervous, opportunistic.',
    profession: 'Street Hustler',
    speakingStyle: 'Fast-talking, stuttering when nervous, slangy.',
    moralAlignment: 'Chaotic Neutral',
    preferredIndustries: ['Entertainment', 'Logistics'],
    strengths: ['Luck', 'Finding Gaps'],
    weaknesses: ['Gambling Addiction', 'Poor Credit'],
    relationshipTags: ['Informant', 'Liability'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET'],
    initialStatus: 'alive'
  },
  {
    id: 'char_rosa',
    name: 'Rosa Mendez',
    nickname: 'Mama Rosa',
    portraitId: 'av_f1',
    background: 'The heart of the block. If you\'re hungry, she feeds you. If you\'re causing trouble, she clips your ear.',
    personality: 'Nurturing, fierce, organized.',
    profession: 'Matriarch',
    speakingStyle: 'Warm but firm, switches between languages.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Food', 'Retail'],
    strengths: ['Local Influence', 'Logistical Coordination'],
    weaknesses: ['Family Loyalty', 'Emotional Decision Making'],
    relationshipTags: ['Community Leader', 'Protector'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP'],
    initialStatus: 'alive'
  },
  {
    id: 'char_twitch',
    name: 'Kevin "Twitch" Miller',
    nickname: 'Twitch',
    portraitId: 'av_m1',
    background: 'The fastest delivery runner in the district. He knows every shortcut and every police blind spot.',
    personality: 'Hyperactive, anxious, reliable.',
    profession: 'Courier',
    speakingStyle: 'Rapid-fire, distracted, jargon-heavy.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Logistics', 'Transport'],
    strengths: ['Speed', 'Geographic Knowledge'],
    weaknesses: ['Short Attention Span', 'Easily Spooked'],
    relationshipTags: ['Runner', 'Early Ally'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP'],
    initialStatus: 'alive'
  },
  {
    id: 'char_miller_cop',
    name: 'Officer Frank Miller',
    nickname: 'Frankie',
    portraitId: 'av_m4',
    background: 'A beat cop who actually cares about the community. He tries to steer kids away from the life.',
    personality: 'Dutiful, tired, hopeful.',
    profession: 'Police Officer',
    speakingStyle: 'Methodical, cautionary, weary.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Security', 'Legal'],
    strengths: ['Legal Insight', 'Crisis Management'],
    weaknesses: ['Bureaucratic Limits', 'Cynical Peers'],
    relationshipTags: ['Law Enforcement', 'Moral Compass'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_jdog',
    name: 'Jermaine "J-Dog" Washington',
    nickname: 'J-Dog',
    portraitId: 'av_m2',
    background: 'An aspiring rapper who spends more time promoting his "brand" than recording music.',
    personality: 'Ambitious, delusional, energetic.',
    profession: 'Aspiring Artist',
    speakingStyle: 'Loud, self-promoting, use of catchphrases.',
    moralAlignment: 'Chaotic Neutral',
    preferredIndustries: ['Entertainment', 'Retail'],
    strengths: ['Self-Confidence', 'Social Networking'],
    weaknesses: ['Lack of Talent', 'Poor Financial Planning'],
    relationshipTags: ['Hustler', 'Social Media Contact'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_cassie',
    name: 'Cassandra "Cassie" Thorne',
    nickname: 'Cass',
    portraitId: 'av_f3',
    background: 'Runs a successful thrift shop that doubles as a hub for local information exchange.',
    personality: 'Observant, witty, guarded.',
    profession: 'Small Business Owner',
    speakingStyle: 'Sarcastic, insightful, quiet.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Retail', 'Media'],
    strengths: ['Information Brokering', 'Market Intuition'],
    weaknesses: ['Isolationist', 'Trust Issues'],
    relationshipTags: ['Informant', 'Business Contact'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_vinnie',
    name: 'Vincent "Vinnie" Moretti',
    nickname: 'Big V',
    portraitId: 'av_m1',
    background: 'Enforcer for a local loan shark. He\'s not mean, he\'s just doing his job.',
    personality: 'Stoic, disciplined, surprisingly gentle.',
    profession: 'Enforcer',
    speakingStyle: 'Brief, polite, intimidating.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Security', 'Finance'],
    strengths: ['Physical Presence', 'Reliability'],
    weaknesses: ['Lack of Initiative', 'Strict Code of Conduct'],
    relationshipTags: ['Underworld Muscle', 'Antagonist'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP'],
    initialStatus: 'alive'
  },
  {
    id: 'char_beatrice',
    name: 'Beatrice Vance',
    nickname: 'Bea',
    portraitId: 'av_f2',
    background: 'A nurse at the underfunded city clinic. She sees the human cost of the city\'s greed every day.',
    personality: 'Resilient, empathetic, blunt.',
    profession: 'Registered Nurse',
    speakingStyle: 'Direct, clinical, compassionate.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Philanthropy', 'Public Service'],
    strengths: ['Crisis Stability', 'Human Perspective'],
    weaknesses: ['Chronic Fatigue', 'Limited Resources'],
    relationshipTags: ['Community Advocate', 'Medical Contact'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP'],
    initialStatus: 'alive'
  },
  {
    id: 'char_ray',
    name: 'Raymond "Ray" Strode',
    nickname: 'Sarge',
    portraitId: 'av_m3',
    background: 'A military veteran who found himself on the streets. Now runs a tactical security consulting firm for local shops.',
    personality: 'Disciplined, paranoid, loyal.',
    profession: 'Security Consultant',
    speakingStyle: 'Tactical, concise, suspicious.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Security', 'Manufacturing'],
    strengths: ['Tactical Planning', 'Loyalty'],
    weaknesses: ['PTSD', 'Difficulty with Civilians'],
    relationshipTags: ['Security Expert', 'Ally'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_lexi',
    name: 'Lexi "Ghost" Chen',
    nickname: 'Lex',
    portraitId: 'av_f4',
    background: 'A street artist whose murals often contain hidden messages about corporate corruption.',
    personality: 'Rebellious, creative, elusive.',
    profession: 'Street Artist',
    speakingStyle: 'Metaphorical, passionate, guarded.',
    moralAlignment: 'Chaotic Good',
    preferredIndustries: ['Entertainment', 'Media'],
    strengths: ['Creative Vision', 'Underground Fame'],
    weaknesses: ['Recklessness', 'Anti-Authority Bias'],
    relationshipTags: ['Activist', 'Cultural Contact'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_dante',
    name: 'Dante Russo',
    portraitId: 'av_m2',
    background: 'The head bouncer at the city\'s most exclusive underground clubs. He decides who is "in" and who is "out".',
    personality: 'Judgmental, calm, observant.',
    profession: 'Head Bouncer',
    speakingStyle: 'Flat, authoritative, dismissing.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Entertainment', 'Security'],
    strengths: ['Gatekeeping', 'Threat Assessment'],
    weaknesses: ['Materialistic', 'Strict Adherence to Rules'],
    relationshipTags: ['Gatekeeper', 'Social Connector'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_lila',
    name: 'Lila Hart',
    portraitId: 'av_f2',
    background: 'A junior clerk at a prestigious law firm who "borrows" interesting documents for the right price.',
    personality: 'Ambitious, nervous, sharp.',
    profession: 'Legal Clerk',
    speakingStyle: 'Nervous, technical, hurried.',
    moralAlignment: 'Neutral Evil',
    preferredIndustries: ['Legal', 'Finance'],
    strengths: ['Document Access', 'Attention to Detail'],
    weaknesses: ['Cowardice', 'Over-ambition'],
    relationshipTags: ['Insider Source', 'Liability'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_bigg',
    name: 'Gustav "Big G" Schmidt',
    nickname: 'Big G',
    portraitId: 'av_m1',
    background: 'The owner of the largest scrap yard in the city. If you need it gone, he takes it. If you need it found, he has it.',
    personality: 'Jovial, greedy, practical.',
    profession: 'Scrap Yard Owner',
    speakingStyle: 'Loud, boisterous, transactional.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Manufacturing', 'Logistics'],
    strengths: ['Resource Availability', 'Physical Assets'],
    weaknesses: ['Greed', 'Environmental Violations'],
    relationshipTags: ['Supplier', 'Logistics Contact'],
    firstAppearanceTier: 'MUD',
    futureAppearanceTiers: ['STREET', 'STARTUP'],
    initialStatus: 'alive'
  },
  {
    id: 'char_tessa',
    name: 'Tessa Brooks',
    portraitId: 'av_f4',
    background: 'A local blogger who covers neighborhood news. She has a small but extremely loyal following.',
    personality: 'Inquisitive, idealistic, relentless.',
    profession: 'Neighborhood Blogger',
    speakingStyle: 'Enthusiastic, questioning, digital-focused.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Media', 'Entertainment'],
    strengths: ['Local Trust', 'Social Media Savvy'],
    weaknesses: ['Lack of Funding', 'Safety Risks'],
    relationshipTags: ['Media Contact', 'Grassroots Voice'],
    firstAppearanceTier: 'STREET',
    futureAppearanceTiers: ['STARTUP', 'CORPORATE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_clark',
    name: 'Alistair Clark',
    nickname: 'The Closer',
    portraitId: 'av_m4',
    background: 'A high-powered corporate lawyer who specializes in "aggressive litigation" and NDA enforcement.',
    personality: 'Ruthless, precise, arrogant.',
    profession: 'Corporate Lawyer',
    speakingStyle: 'Legalistic, threateningly calm, precise.',
    moralAlignment: 'Lawful Evil',
    preferredIndustries: ['Legal', 'Finance', 'Corporate'],
    strengths: ['Legal Warfare', 'Contract Manipulation'],
    weaknesses: ['Public Scrutiny', 'Bureaucratic Red Tape'],
    relationshipTags: ['Legal Shield', 'Fixer'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_summers',
    name: 'Brooke Summers',
    nickname: 'Sunny',
    portraitId: 'av_f2',
    background: 'A digital native who transformed a social media empire into a venture capital powerhouse. She represents the "New Money" shift—where public perception and viral clout are just as valuable as liquid assets.',
    personality: 'Savvy, trend-obsessed, surprisingly ruthless when the cameras are off.',
    profession: 'Venture Capitalist',
    speakingStyle: 'High-energy, trend-focused, optimistic.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Technology', 'Entertainment', 'Retail'],
    strengths: ['Brand Building', 'Consumer Trends'],
    weaknesses: ['Short-term Hype', 'Over-extension'],
    relationshipTags: ['Investor', 'Marketing Partner'],
    firstAppearanceTier: 'STARTUP',
    futureAppearanceTiers: ['CORPORATE', 'ELITE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_khalid',
    name: 'Khalid Al-Mansour',
    portraitId: 'av_m1',
    background: 'A logistics mogul who controls the flow of goods through the city\'s major ports.',
    personality: 'Pragmatic, influential, traditional.',
    profession: 'Logistics Titan',
    speakingStyle: 'Measured, authoritative, respectful.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Logistics', 'Transport', 'Manufacturing'],
    strengths: ['Supply Chain Control', 'Global Network'],
    weaknesses: ['Regulatory Scrutiny', 'Labor Disputes'],
    relationshipTags: ['Strategic Partner', 'Industry Peer'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_julian',
    name: 'Julian Vane',
    nickname: 'The Architect',
    portraitId: 'av_m4',
    background: 'A brilliant urban planner who is secretly redesigning the city to benefit a small group of elites.',
    personality: 'Visionary, manipulative, detached.',
    profession: 'Urban Planner',
    speakingStyle: 'Abstract, intellectual, condescending.',
    moralAlignment: 'Lawful Evil',
    preferredIndustries: ['Real Estate', 'Construction', 'Politics'],
    strengths: ['Zoning Control', 'Strategic Vision'],
    weaknesses: ['Public Protests', 'Unforeseen Variables'],
    relationshipTags: ['Hidden Hand', 'Rival'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_elara',
    name: 'Elara Moon',
    portraitId: 'av_f4',
    background: 'A former hacker who now runs a premier cybersecurity firm catering to the world\'s 1%.',
    personality: 'Protective, sharp, secretive.',
    profession: 'Cybersecurity CEO',
    speakingStyle: 'Technical, cautious, whisper-quiet.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Technology', 'Security'],
    strengths: ['Digital Defense', 'Privacy Management'],
    weaknesses: ['Zero-day Vulnerabilities', 'Insider Threats'],
    relationshipTags: ['Security Expert', 'Confidant'],
    firstAppearanceTier: 'STARTUP',
    futureAppearanceTiers: ['CORPORATE', 'ELITE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_garrett',
    name: 'Garrett Thorne',
    nickname: 'The Hammer',
    portraitId: 'av_m3',
    background: 'A union-busting consultant who is brought in to "stabilize" labor relations during mergers.',
    personality: 'Aggressive, intimidating, efficient.',
    profession: 'Labor Consultant',
    speakingStyle: 'Blunt, loud, confrontational.',
    moralAlignment: 'Neutral Evil',
    preferredIndustries: ['Manufacturing', 'Transport', 'Corporate'],
    strengths: ['Intimidation', 'Psychological Warfare'],
    weaknesses: ['Legal Challenges', 'Violent Retaliation'],
    relationshipTags: ['Mercenary', 'Fixer'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_selena',
    name: 'Selena Rosso',
    nickname: 'The Siren',
    portraitId: 'av_f1',
    background: 'A world-famous pop star who uses her platform to influence global social policy.',
    personality: 'Magnetic, idealistic, temperamental.',
    profession: 'Pop Star',
    speakingStyle: 'Charismatic, emotional, inspirational.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Entertainment', 'Philanthropy', 'Media'],
    strengths: ['Mass Persuasion', 'Aura Generation'],
    weaknesses: ['Public Scandals', 'Emotional Volatility'],
    relationshipTags: ['Celebrity Ally', 'Cultural Icon'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_hudson',
    name: 'Hudson Reed',
    nickname: 'The Oracle',
    portraitId: 'av_m4',
    background: 'A reclusive mathematician whose algorithms can predict market shifts with terrifying accuracy.',
    personality: 'Obsessive, brilliant, socially awkward.',
    profession: 'Quant Analyst',
    speakingStyle: 'Mathematical, detached, fragmented.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Finance', 'Technology'],
    strengths: ['Predictive Modeling', 'Data Analysis'],
    weaknesses: ['Social Interaction', 'Sensory Overload'],
    relationshipTags: ['Strategic Asset', 'Mentor'],
    firstAppearanceTier: 'STARTUP',
    futureAppearanceTiers: ['CORPORATE', 'ELITE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_naomi',
    name: 'Naomi West',
    portraitId: 'av_f3',
    background: 'A PR genius who can turn even the most devastating scandal into a positive branding opportunity.',
    personality: 'Polished, manipulative, tireless.',
    profession: 'PR Consultant',
    speakingStyle: 'Smooth, persuasive, jargon-heavy.',
    moralAlignment: 'Neutral Evil',
    preferredIndustries: ['Media', 'Public Relations', 'Politics'],
    strengths: ['Crisis Management', 'Image Crafting'],
    weaknesses: ['Truth', 'Leaked Communications'],
    relationshipTags: ['Image Consultant', 'Fixer'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_bennett',
    name: 'Arthur Bennett',
    nickname: 'The Dean',
    portraitId: 'av_m3',
    background: 'The Dean of the city\'s most prestigious business school. He shapes the minds of future leaders.',
    personality: 'Traditional, scholarly, influential.',
    profession: 'Academic Dean',
    speakingStyle: 'Formal, academic, slow.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Education', 'Politics', 'Finance'],
    strengths: ['Networking', 'Academic Prestige'],
    weaknesses: ['Old-fashioned Views', 'Bureaucracy'],
    relationshipTags: ['Mentor', 'Gatekeeper'],
    firstAppearanceTier: 'STARTUP',
    futureAppearanceTiers: ['CORPORATE', 'ELITE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_fiona',
    name: 'Fiona Glass',
    portraitId: 'av_f4',
    background: 'An investigative auditor who specializes in uncovering white-collar crime within Fortune 500 companies.',
    personality: 'Relentless, analytical, incorruptible.',
    profession: 'Forensic Auditor',
    speakingStyle: 'Dry, factual, interrogative.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Finance', 'Legal', 'Corporate'],
    strengths: ['Financial Forensics', 'Unwavering Ethics'],
    weaknesses: ['Lack of Political Savvy', 'Strict Protocol'],
    relationshipTags: ['Watchdog', 'Threat'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_sterling',
    name: 'Sterling Vane',
    nickname: 'The Heir',
    portraitId: 'av_m1',
    background: 'A distant cousin who inherited a massive fortune and is now using it to buy his way into every industry you enter.',
    personality: 'Entitled, competitive, insecure.',
    profession: 'Venture Capitalist',
    speakingStyle: 'Entitled, informal, aggressive.',
    moralAlignment: 'Chaotic Evil',
    preferredIndustries: ['Finance', 'Real Estate', 'Entertainment'],
    strengths: ['Unlimited Capital', 'Family Connections'],
    weaknesses: ['Inexperience', 'Fragile Ego'],
    relationshipTags: ['Family Rival', 'Industry Competitor'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'rival'
  },
  {
    id: 'char_ivy',
    name: 'Ivy Chen',
    portraitId: 'av_f1',
    background: 'A biotech pioneer whose research into neural interfaces could change the definition of what it means to be human.',
    personality: 'Idealistic, brilliant, intense.',
    profession: 'Biotech Scientist',
    speakingStyle: 'Intellectual, passionate, visionary.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Technology', 'Manufacturing'],
    strengths: ['Scientific Innovation', 'Long-term Vision'],
    weaknesses: ['Ethical Dilemmas', 'Funding Dependence'],
    relationshipTags: ['Strategic Partner', 'Visionary'],
    firstAppearanceTier: 'STARTUP',
    futureAppearanceTiers: ['CORPORATE', 'ELITE'],
    initialStatus: 'alive'
  },
  {
    id: 'char_dominic',
    name: 'Dominic Russo',
    nickname: 'Dom',
    portraitId: 'av_m2',
    background: 'A high-end private security contractor who handles protection for VIPs and "sensitive" transport.',
    personality: 'Disciplined, observant, loyal.',
    profession: 'Security Specialist',
    speakingStyle: 'Professional, brief, tactical.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Security', 'Logistics', 'Transport'],
    strengths: ['Physical Security', 'Logistical Precision'],
    weaknesses: ['Limited Strategic Scope', 'Strict Honor Code'],
    relationshipTags: ['Security Expert', 'Ally'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_camille',
    name: 'Camille Dubois',
    portraitId: 'av_f3',
    background: 'The editor-in-chief of the city\'s most influential fashion and lifestyle magazine.',
    personality: 'Sophisticated, judgmental, powerful.',
    profession: 'Editor-in-Chief',
    speakingStyle: 'Refined, critical, fast-paced.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Media', 'Retail', 'Entertainment'],
    strengths: ['Cultural Gatekeeping', 'Trend Analysis'],
    weaknesses: ['Elitism', 'Sensitivity to Public Opinion'],
    relationshipTags: ['Media Gatekeeper', 'Social Connector'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_xavier',
    name: 'Xavier Thorne',
    nickname: 'The Ghost Maker',
    portraitId: 'av_m4',
    background: 'A former intelligence officer who now specializes in erasing people\'s digital and physical identities.',
    personality: 'Paranoid, meticulous, detached.',
    profession: 'Identity Specialist',
    speakingStyle: 'Cryptic, low-volume, direct.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Security', 'Legal', 'Technology'],
    strengths: ['Operational Security', 'Discretion'],
    weaknesses: ['Extreme Paranoia', 'Limited Trust'],
    relationshipTags: ['Shadow Asset', 'Fixer'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_olivia',
    name: 'Olivia West',
    portraitId: 'av_f2',
    background: 'A lobbyist who represents the interests of the energy sector. She knows exactly which pockets to line.',
    personality: 'Charismatic, ruthless, pragmatic.',
    profession: 'Lobbyist',
    speakingStyle: 'Persuasive, friendly, transactional.',
    moralAlignment: 'Neutral Evil',
    preferredIndustries: ['Energy', 'Politics', 'Finance'],
    strengths: ['Political Access', 'Negotiation'],
    weaknesses: ['Ethical Scandals', 'Regulatory Overhaul'],
    relationshipTags: ['Political Broker', 'Industry Contact'],
    firstAppearanceTier: 'CORPORATE',
    futureAppearanceTiers: ['ELITE', 'MOGUL'],
    initialStatus: 'alive'
  },
  {
    id: 'char_marcus_v2',
    name: 'Marcus "The Mook" Miller',
    nickname: 'Boss Marcus',
    portraitId: 'av_m1',
    background: 'Years after the mud blocks, Marcus has traded his street-corner dealings for high-stakes underworld influence. He remains your most loyal, if dangerous, childhood connection.',
    personality: 'Commanding, weary of the life, fiercely protective of his "family".',
    profession: 'Underworld Kingpin',
    speakingStyle: 'Authoritative, calm, slang-aware.',
    moralAlignment: 'Chaotic Neutral',
    preferredIndustries: ['Logistics', 'Security', 'Entertainment'],
    strengths: ['Underworld Loyalty', 'Tactical Experience'],
    weaknesses: ['Old Grudges', 'Legal Vulnerability'],
    relationshipTags: ['Ally', 'Underworld Contact'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_maya_v2',
    name: 'Maya Vane',
    nickname: 'Senator Vane',
    portraitId: 'av_f1',
    background: 'Your younger sister has grown into a formidable political force. The idealism of the community center has been tempered by the reality of Senate floor battles, but her moral compass remains sharp—often pointing directly at your empire.',
    personality: 'Sharp-tongued, weary but resilient, uncompromising.',
    profession: 'State Senator',
    speakingStyle: 'Inspirational, direct, principled.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Politics', 'Philanthropy', 'Public Service'],
    strengths: ['Popular Support', 'Moral Authority'],
    weaknesses: ['Political Infighting', 'Family Compromises'],
    relationshipTags: ['Family', 'Political Force'],
    firstAppearanceTier: 'ELITE',
    futureAppearanceTiers: ['MOGUL', 'PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_victor_v2',
    name: 'Victor Kane',
    nickname: 'Chairman Kane',
    portraitId: 'av_m2',
    background: 'Once a mere corporate rival, Kane has ascended into the global stratosphere. He no longer seeks to beat you in a market; he seeks to erase your name from history itself.',
    personality: 'Nihilistic, transcendental, absolute.',
    profession: 'Global Chairman',
    speakingStyle: 'Cold, philosophical, absolute.',
    moralAlignment: 'Lawful Evil',
    preferredIndustries: ['Finance', 'Technology', 'Energy'],
    strengths: ['Global Influence', 'Technological Dominance'],
    weaknesses: ['Disconnect from Reality', 'Institutional Inertia'],
    relationshipTags: ['Arch-Rival', 'Global Player'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT'],
    initialStatus: 'rival'
  },
  {
    id: 'char_whitaker',
    name: 'General Silas Whitaker',
    portraitId: 'av_m3',
    background: 'A four-star general and Chairman of the Joint Chiefs. He views the nation\'s economy as a matter of national security.',
    personality: 'Disciplined, strategic, blunt.',
    profession: 'Military Advisor',
    speakingStyle: 'Commanding, concise, acronym-heavy.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Security', 'Manufacturing', 'Technology'],
    strengths: ['Military Intel', 'Strategic Planning'],
    weaknesses: ['Rigid Thinking', 'Disregard for Civilian Cost'],
    relationshipTags: ['Military Advisor', 'Cabinet Member'],
    firstAppearanceTier: 'PRESIDENT',
    futureAppearanceTiers: ['OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_vance_sr',
    name: 'Eleanor Vance Sr.',
    nickname: 'The Matriarch',
    portraitId: 'av_f3',
    background: 'The true power behind the Vance family fortune. She has seen presidents come and go, and she isn\'t impressed by you.',
    personality: 'Haughty, brilliant, patient.',
    profession: 'Billionaire Matriarch',
    speakingStyle: 'Refined, quiet, devastatingly sharp.',
    moralAlignment: 'Lawful Evil',
    preferredIndustries: ['Finance', 'Real Estate', 'Politics'],
    strengths: ['Generational Wealth', 'Political History'],
    weaknesses: ['Family Scandals', 'Changing Social Values'],
    relationshipTags: ['Industry Titan', 'Rival'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_tanaka',
    name: 'Prime Minister Kenji Tanaka',
    portraitId: 'av_m4',
    background: 'The leader of a key economic ally. He is a master of soft power and subtle negotiation.',
    personality: 'Diplomatic, observant, firm.',
    profession: 'Foreign Leader',
    speakingStyle: 'Soft-spoken, polite, indirect.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Technology', 'Manufacturing', 'Finance'],
    strengths: ['Diplomatic Leverage', 'Trade Alliances'],
    weaknesses: ['Domestic Politics', 'Economic Dependence'],
    relationshipTags: ['Foreign Ally', 'Global Peer'],
    firstAppearanceTier: 'PRESIDENT',
    futureAppearanceTiers: ['OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_holloway',
    name: 'Judge Margaret Holloway',
    portraitId: 'av_f4',
    background: 'A Supreme Court justice known for her strict interpretation of corporate law. She is the final hurdle for your most ambitious plans.',
    personality: 'Impartial, intellectual, formidable.',
    profession: 'Supreme Court Justice',
    speakingStyle: 'Formal, precise, inquisitive.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Legal', 'Politics'],
    strengths: ['Judicial Power', 'Legal Integrity'],
    weaknesses: ['Lack of Enforcement Power', 'Public Perception'],
    relationshipTags: ['Judicial Authority', 'Gatekeeper'],
    firstAppearanceTier: 'PRESIDENT',
    futureAppearanceTiers: ['OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_blackwood',
    name: 'Director Elias Blackwood',
    nickname: 'The Spymaster',
    portraitId: 'av_m3',
    background: 'The Director of National Intelligence. He knows things about you that even you have forgotten.',
    personality: 'Secretive, cynical, omnipresent.',
    profession: 'Intelligence Director',
    speakingStyle: 'Whispered, cryptic, knowing.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Security', 'Technology', 'Media'],
    strengths: ['Total Surveillance', 'Blackmail Material'],
    weaknesses: ['Legislative Oversight', 'Internal Leaks'],
    relationshipTags: ['Intelligence Contact', 'Cabinet Member'],
    firstAppearanceTier: 'PRESIDENT',
    futureAppearanceTiers: ['OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_stone',
    name: 'Marcus Stone',
    nickname: 'The Kingmaker',
    portraitId: 'av_m1',
    background: 'A legendary campaign manager who has never lost an election. He is ruthless, brilliant, and completely amoral.',
    personality: 'Cynical, high-energy, predatory.',
    profession: 'Campaign Manager',
    speakingStyle: 'Rapid-fire, aggressive, use of sports metaphors.',
    moralAlignment: 'Chaotic Evil',
    preferredIndustries: ['Politics', 'Media', 'Public Relations'],
    strengths: ['Voter Manipulation', 'Opposition Research'],
    weaknesses: ['Public Infamy', 'Lack of Loyalty'],
    relationshipTags: ['Campaign Staff', 'Fixer'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_dupris',
    name: 'Jean-Pierre Dupris',
    portraitId: 'av_m2',
    background: 'A European central banker who controls the flow of the world\'s reserve currency.',
    personality: 'Arrogant, calculating, influential.',
    profession: 'Central Banker',
    speakingStyle: 'Sophisticated, bored, authoritative.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Finance', 'Politics'],
    strengths: ['Monetary Policy', 'Global Credit Control'],
    weaknesses: ['Inflationary Pressures', 'Populist Uprisings'],
    relationshipTags: ['Financial Power', 'Global Peer'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT', 'OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_chen_sr',
    name: 'Elder Chen',
    nickname: 'The Patriarch',
    portraitId: 'av_m4',
    background: 'Lawrence Chen\'s father and the founder of the Chen dynasty. He views business as a form of spiritual practice.',
    personality: 'Philosophical, patient, formidable.',
    profession: 'Retired Industrialist',
    speakingStyle: 'Proverb-heavy, quiet, intense.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Manufacturing', 'Technology', 'Philanthropy'],
    strengths: ['Traditional Wisdom', 'Global Respect'],
    weaknesses: ['Physical Frailty', 'Old World Methods'],
    relationshipTags: ['Mentor', 'Family Patriarch'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT', 'OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_valdez',
    name: 'Secretary Elena Valdez',
    portraitId: 'av_f3',
    background: 'The Secretary of State. She is a master of the "grand bargain" and is currently negotiating a massive new trade deal.',
    personality: 'Charismatic, pragmatic, tireless.',
    profession: 'Secretary of State',
    speakingStyle: 'Eloquent, persuasive, multicultural.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Politics', 'Logistics', 'Energy'],
    strengths: ['Diplomatic Skill', 'International Network'],
    weaknesses: ['Domestic Criticism', 'Geopolitical Shifts'],
    relationshipTags: ['Cabinet Member', 'Political Ally'],
    firstAppearanceTier: 'PRESIDENT',
    futureAppearanceTiers: ['OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_thornton',
    name: 'William Thornton',
    nickname: 'The Baron',
    portraitId: 'av_m1',
    background: 'A media mogul who owns three major news networks and use them to shape the national narrative.',
    personality: 'Vain, manipulative, powerful.',
    profession: 'Media Mogul',
    speakingStyle: 'Authoritative, sensational, loud.',
    moralAlignment: 'Neutral Evil',
    preferredIndustries: ['Media', 'Entertainment', 'Politics'],
    strengths: ['Narrative Control', 'Public Influence'],
    weaknesses: ['Changing Tech Trends', 'Regulatory Antitrust'],
    relationshipTags: ['Media Power', 'Rival'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_ross',
    name: 'Diana Ross',
    nickname: 'The Hammer',
    portraitId: 'av_f2',
    background: 'The most feared corporate auditor in the world. When she enters a building, CEOs start resigning.',
    personality: 'Cold, precise, relentless.',
    profession: 'Lead Auditor',
    speakingStyle: 'Clinical, monotone, direct.',
    moralAlignment: 'Lawful Neutral',
    preferredIndustries: ['Finance', 'Corporate', 'Legal'],
    strengths: ['Financial Forensics', 'Psychological Pressure'],
    weaknesses: ['Bureaucratic Hurdles', 'Political Interference'],
    relationshipTags: ['Watchdog', 'Threat'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT'],
    initialStatus: 'alive'
  },
  {
    id: 'char_adler',
    name: 'Dr. Hans Adler',
    portraitId: 'av_m4',
    background: 'A Nobel-winning economist who serves as your chief economic advisor. His theories are brilliant but often disconnected from the street.',
    personality: 'Academic, eccentric, brilliant.',
    profession: 'Economic Advisor',
    speakingStyle: 'Complex, abstract, enthusiastic.',
    moralAlignment: 'True Neutral',
    preferredIndustries: ['Finance', 'Politics', 'Education'],
    strengths: ['Economic Theory', 'Data Forecasting'],
    weaknesses: ['Political Naivety', 'Over-reliance on Models'],
    relationshipTags: ['Advisor', 'Cabinet Member'],
    firstAppearanceTier: 'PRESIDENT',
    futureAppearanceTiers: ['OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_singh',
    name: 'Anya Singh',
    portraitId: 'av_f4',
    background: 'The CEO of the world\'s largest space exploration company. She is already looking past Earth.',
    personality: 'Visionary, intense, risk-tolerant.',
    profession: 'Space CEO',
    speakingStyle: 'Future-focused, technical, inspiring.',
    moralAlignment: 'Neutral Good',
    preferredIndustries: ['Technology', 'Manufacturing', 'Energy'],
    strengths: ['Technological Innovation', 'Long-term Planning'],
    weaknesses: ['Resource Intensive', 'Regulatory Risks'],
    relationshipTags: ['Industry Peer', 'Visionary Ally'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT', 'OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_morozov',
    name: 'Ivan Morozov',
    nickname: 'The Ghost',
    portraitId: 'av_m3',
    background: 'A former shadow-state operative who leveraged chaos into a global energy monopoly. He is the ultimate test of your resolve—a man who views entire nations as disposable assets.',
    personality: 'Patient, predatory, utterly detached from human empathy.',
    profession: 'Global Oligarch',
    speakingStyle: 'Low-volume, heavy accent, threatening.',
    moralAlignment: 'Chaotic Evil',
    preferredIndustries: ['Energy', 'Security', 'Technology'],
    strengths: ['Shadow Networks', 'Ruthless Enforcement'],
    weaknesses: ['International Sanctions', 'Betrayal from Within'],
    relationshipTags: ['Global Threat', 'Rival'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT', 'OPEN'],
    initialStatus: 'alive'
  },
  {
    id: 'char_lane',
    name: 'Sarah Lane',
    portraitId: 'av_f1',
    background: 'A grassroots activist who has successfully blocked several of your major projects. She is the voice of the people you left behind.',
    personality: 'Courageous, articulate, relentless.',
    profession: 'Activist Leader',
    speakingStyle: 'Passionate, moralistic, sharp.',
    moralAlignment: 'Lawful Good',
    preferredIndustries: ['Philanthropy', 'Politics', 'Media'],
    strengths: ['Public Support', 'Moral Clarity'],
    weaknesses: ['Lack of Funding', 'Target of Smear Campaigns'],
    relationshipTags: ['Political Antagonist', 'Moral Voice'],
    firstAppearanceTier: 'MOGUL',
    futureAppearanceTiers: ['PRESIDENT'],
    initialStatus: 'alive'
  }
];
