export const GAME_CONSTANTS = {
  SABOTAGE_COST: 500000,
  LEGACY_MULTIPLIER_BASE: 0.001,
  TICKER_MAX_MESSAGES: 50,
  ACTION_LOG_MAX_SIZE: 500,
  TUTORIAL_LOCAL_STORAGE_KEY: 'bag-chaser-tutorial-complete',
  SAVE_GAME_LOCAL_STORAGE_KEY: 'bag-chaser-save',
  ENDINGS_LOCAL_STORAGE_KEY: 'bag-chaser-endings',
  NOMINATION_DELEGATES_REQUIRED: 1991,
};
